name: Deploy

on:
  push:
    branches:
      - main
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  deploy:
    if: github.repository_owner == 'hugovk'
    runs-on: ubuntu-latest

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"
          cache: pip
          cache-dependency-path: pyproject.toml

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U build twine wheel

      - name: Build package
        run: |
          python -m build
          twine check --strict dist/*

      - name: Publish package to PyPI
        if: github.event.action == 'published'
        uses: pypa/gh-action-pypi-publish@release/v1

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
